apiVersion: batch/v1beta1
kind: CronJob
metadata:   
  name: dbupdater
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbupdater
            image: skyblade/rssfilter.dbupdater:latest
            volumeMounts:
            - mountPath: /app/db
              name: db
          restartPolicy: OnFailure
          volumes:
          - name: db
            persistentVolumeClaim:
              claimName: db
