version: '3.4'

services:
  rssfilter:
    image: ${DOCKER_REGISTRY-}rssfilter
    build:
      context: .
      dockerfile: RssFilter/Dockerfile
    volumes:
      - db:/app/db


  dbupdater:
    image: ${DOCKER_REGISTRY-}dbupdater
    build:
      context: .
      dockerfile: DbUpdater/Dockerfile
    volumes:
      - db:/app/db
volumes:
  db:
